import Head from 'next/head'
import Image from 'next/image'
import { Geist, Geist_Mono } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { Button, Sheet, Typography } from '@mui/joy'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Music League</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div className={styles.ctas}>
            <Sheet>
              <Typography level="h1">Yed Heads</Typography>
              <Link href={'/yed-heads/upcoming-rounds'}>
                <Button>Upcoming Rounds</Button>
              </Link>
              <Link href={'/yed-heads/submit-idea'}>
                <Button>Submit An Idea</Button>
              </Link>
            </Sheet>
          </div>
        </main>
        <footer className={styles.footer}></footer>
      </div>
    </>
  )
}
